name: CI

on: [push, pull_request]

jobs:
  testsuite:
    name: Unittests
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4']

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, json, fileinfo
          tools: pecl
          coverage: pcov

      - name: Composer install
        run: |
          if [[ ${{ matrix.prefer-lowest == 'prefer-lowest' }} ]]; then
            composer update --prefer-stable
          else
            composer install
          fi

      - name: Run PHPUnit
        run: |
          if [[ ${{ matrix.php-version }} == '8.3' ]]; then
            bin/phpunit --coverage-clover=coverage.xml
          else
            bin/phpunit
          fi

      - name: Code Coverage Report
        if: success() && matrix.php-version == '8.3'
        uses: codecov/codecov-action@v4

  phpstan:
    name: PHPStan
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, json, fileinfo

      - name: Composer install
        run: composer install

      - name: Run PHPStan
        run: bin/phpstan analyse --no-progress

  phpcs:
    name: PHPCS
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, json, fileinfo

      - name: Composer install
        run: composer install

      - name: Run PHPCS
        run: bin/phpcs --report=source --standard=phpcs.xml
